CREATE DATABASE PROJETO_FORTES;
USE PROJETO_FORTES;


CREATE TABLE IF NOT EXISTS USUARIO(
    USUARIO_ID INT PRIMARY KEY,
    USUARIO_NOME VARCHAR(45) NOT NULL,
    USUARIO_EMAIL VARCHAR(45) NOT NULL,
    USUARIO_RUA VARCHAR(100) NOT NULL,
    USUARIO_NUMRUA INT,
    USUARIO_BAIRRO VARCHAR(45) NOT NULL,
    USUARIO_CIDADE VARCHAR(45) NOT NULL,
    USUARIO_ESTADO VARCHAR(45) NOT NULL
);


CREATE TABLE IF NOT EXISTS COMPROVANTES(
    COMP_ID INT PRIMARY KEY,
    COMP_DATA_ENVIO DATE NOT NULL
);


CREATE TABLE IF NOT EXISTS STATUS_PROJ(
    STATUS_ID INT PRIMARY KEY,
    STATUS_DESC ENUM('EM ANALISE', 'APROVADO', 'REJEITADO'),
    STATUS_DATA_SUBMISSAO DATE NOT NULL
);


CREATE TABLE IF NOT EXISTS PROJETOS(
    PROJ_ID INT PRIMARY KEY,
    PROJ_NOME VARCHAR(45) NOT NULL,
    PROJ_DESCRICAO TEXT NOT NULL,
    PROJ_DATA_SUBMISSAO DATE NOT NULL,
    PROJ_USUARIO INT,
    PROJ_COMP INT,
    PROJ_STATUS INT,
    CONSTRAINT FK_USUARIO FOREIGN KEY (PROJ_USUARIO) REFERENCES USUARIO(USUARIO_ID),
    CONSTRAINT FK_COMPROVANTES FOREIGN KEY (PROJ_COMP) REFERENCES COMPROVANTES(COMP_ID),
    CONSTRAINT FK_STATUS_PROJ FOREIGN KEY (PROJ_STATUS) REFERENCES STATUS_PROJ(STATUS_ID)
);