CREATE SCHEMA EC2_SI1N

USE EC2_SI1N

CREATE TABLE IF NOT EXISTS PASSAGEIROS(
PASS_CPF INT PRIMARY KEY,
PASS_NOME VARCHAR(45) NOT NULL,
PASS_TEL INT NOT NULL,
PASS_RUANUM INT NOT NULL,
PASS_BAIRRO VARCHAR(45) NOT NULL,
PASS_CIDADE VARCHAR(45) NOT NULL,
PASS_ESTADO VARCHAR(45) NOT NULL,
PASS_EMAIL VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS VOOS(
VOO_COD INT PRIMARY KEY,
DATAHORA_ORIGEM DATETIME NOT NULL,
DATAHORA_DESTINO DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS AEROPORTOS(
AEROP_COD INT PRIMARY KEY,
AEROP_NOME VARCHAR(45) NOT NULL,
AEROP_LOCAL VARCHAR(45) NOT NULL,
AEROP_PAIS VARCHAR(45) NOT NULL,
AEROP_LONGITUDE DOUBLE NOT NULL,
AEROP_LATITUDE DOUBLE NOT NULL,
);

CREATE TABLE IF NOT EXISTS AERONAVES(
AERONAVE_PREFIXO VARCHAR(10) NOT NULL,
AERONAVE_MODELO VARCHAR(20) NOT NULL,
AERONAVE_ANOFAB INT NOT NULL,
AERONAVE_CAPAC VARCHAR(20) NOT NULL,
AERONAVE_FABRIC VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS(
FUNC_ID INT PRIMARY KEY,
FUNC_FUNCAO VARCHAR(45) NOT NULL,
FUNC_NOME VARCHA(45) NOT NULL,
FUNC_DATANASC DATE NOT NULL,
FUNC_TEL INT NOT NULL
);

CREATE TABLE IF NOT EXISTS RESERVAS(
VOO_COD INT,
PASS_CPF INT,
PRIMARY KEY(VOO_COD, PASS_CPF),
CONSTRAINT VOO_FK_COD FOREIGN KEY(VOO_COD)
REFERENCES VOOS(VOO_COD),
CONSTRAINT PASS_FK_CPF FOREIGN KEY(PASS_CPF)
REFERENCES PASSAGEIROS(PASS_CPF)
);

CREATE TABLE IF NOT EXISTS EQUIPES(
FUNC_ID INT,
VOO_COD INT,
CONSTRAINT FUNC_FK_ID FOREIGN KEY(FUNC_ID)
REFERENCES FUNCIONARIOS(FUNC_ID),
CONSTRAINT VOO_FK_COD FOREIGN KEY(VOO_COD)
REFERENCES VOOS(VOO_COD),
);  




