CREATE SCHEMA EC5_SI1N;

USE ES5_SI1N;

CREATE TABLE IF NOT EXISTS CLIENTES(
CPF_CLIENTE INT PRIMARY KEY,
NOME_CLIENTE VARCHAR(45) NOT NULL,
DATA_NASC_CLIENTE DATE, 
NUM_RUA_CLIENTE INT NOT NULL,
BAIRRO_CLIENTE VARCHAR(45) NOT NULL,
CIDADE_CLIENTE VARCHAR(45) NOT NULL,
ESTADO_CLIENTE VARCHAR(45) NOT NULL,
STATUS_FIDEL_CLIENTE VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTOS(
COD_PROD INT PRIMARY KEY,
NOME_PROD VARCHAR(45) NOT NULL,
ESPEC_PROD TEXT NOT NULL,
CATEGO_PROD VARCHAR(45) NOT NULL,
DISPO_ESTOQUE_PROD VARCHAR(50) NOT NULL,
PRECO_PROD DECIMAL(10,2) NOT NULL,
PROD_FORN INT NOT NULL,
PROD_VENDA INT NOT NULL,
CONSTRAINT FK_FORNECEDOR FOREIGN KEY (PROD_FORN)
REFERENCES FORNECEDORES(ID_FORN)
CONSTRAINT FK_VENDAS FOREIGN KEY (PROD_VENDA)
REFERENCES VENDAS(ID_VENDA)
);

CREATE TABLE IF NOT EXISTS FORNECEDORES(
ID_FORN INT PRIMARY KEY,
TEL_FORN INT NOT NULL,
FORNEC_RUA VARCHAR(45) NOT NULL,
NUM_RUA_FORN VARCHAR(45) NOT NULL,
BAIRRO_FORN VARCHAR(45) NOT NULL,
CIDADE_FORN VARCHAR(45) NOT NULL,
ESTADO_FORN VARCHAR(45) NOT NULL,
PROD_FORN INT NOT NULL
CONSTRAINT FK_PRODUTOS FOREIGN KEY (FORN_PROD)
REFERENCES PRODUTOS(COD_PROD INT)
);

CREATE TABLE IF NOT EXISTS VENDAS(
ID_VENDA INT PRIMARY KEY,
COD_VENDA INT,
CLIENTE_VENDA VARCHAR(45)  NOT NULL,
PROD_VENDA VARCHAR(45 NOT NULL,
FORM_PAG_VENDA VARCHAR(20) NOT NULL,
DATA_VENDA DATE NOT NULL,
VENDA_PROD INT NOT NULL,
CONSTRAINT FK_PRODUTOS FOREIGN KEY (VENDA_PROD)
REFERENCES PRODUTOS(COD_PROD)
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS(
CONFIRM_PAG INT PRIMARY KEY,
DATA_PAG DATE NOT NULL,
HORA_PAG TIME,
VALOR_PAG DECIMAL(10,2) NOT NULL,
);

CREATE TABLE IF NOT EXISTS VENDAS_PRODUTOS(
VDPR_VENDAS INT,
VDPR_PRODUTOS INT,
PRIMARY KEY(VDPR_VENDAS, VDPR_PRODUTOS),
CONSTRAINT VDPR_FK_VENDAS FOREIGN KEY(VDPR_VENDAS)
REFERENCES VENDAS(ID_VENDA),
CONSTRAINT VDPR_FK_PRODUTOS FOREIGN KEY(VDPR_PRODUTOS)
REFERENCES PRODUTOS(COD_PROD));

CREATE TABLE IF NOT EXISTS FORNECEDORES_PRODUTOS(
FRPR_FORNECEDOR INT,
FRPR_PRODUTOS INT,
PRIMARY KEY(FRPR_FORNECEDOR,FRPR_PRODUTOS),
CONSTRAINT FRPR_FK_FORNECEDORES FOREIGN KEY(FRPR_FORNECEDOR)
REFERENCES FORNECEDORES(FORNEC_COD),
CONSTRAINT FRPR_FK_PRODUTOS FOREIGN KEY(FRPR_PRODUTOS) 
REFERENCES PRODUTOS(PROD_COD));

ALTER TABLE CLIENTES ADD EMAIL_CLIENTE VARCHAR(45) NOT NULL;
ALTER TABLE CLIENTES DROP COLUMN DATA_NASC_CLIENTE;
ALTER TABLE CLIENTES MODIFY COLUMN STATUS_FIDEL_CLIENTE VARCHAR(100) NOT NULL;
ALTER TABLE CLIENTES CHANGE COLUMN NOMECOMP_CLIENTE VARCHAR(100) NOT NULL;

ALTER TABLE PRODUTOS ADD DESCRICAO_PROD TEXT NOT NULL;
ALTER TABLE PRODUTOS DROP COLUMN ESPEC_PROD TEXT NOT NULL;
ALTER TABLE PRODUTOS MODIFY COLUMN DISPO_ESTOQUE_PROD TEXT NOT NULL;
ALTER TABLE PRODUTOS CHANGE COLUMN PRECO_PROD PRECOUNI_PROD DECIMAL(10,2) NOT NULL;

ALTER TABLE FORNECEDORES ADD FORNEC_CONTATO TEXT NOT NULL;
ALTER TABLE FORNECEDORES DROP COLUMN FORNEC_RUA VARCHAR(45) NOT NULL;
ALTER TABLE FORNECEDORES MODIFY COLUMN NUM_RUA_FORN INT NOT NULL,
ALTER TABLE FORNECEDORES CHANGE COLUMN  NUM_RUA_FORN NUMRUA_FORN INT NOT NULL;

ALTER TABLE VENDAS ADD HORA_VENDA TIME NOT NULL;
ALTER TABLE VENDAS DROP COLUMN COD_VENDA INT;
ALTER TABLE VENDAS MODIFY COLUMN FORM_PAG_VENDA ENUM('DEBITO', 'CREDITO', 'CASH');
ALTER TABLE VENDAS CHANGE COLUMN FORM_PAG_VENDA FORMPAG_VENDA ENUM('DEBITO', 'CREDITO', 'CASH');

ALTER TABLE PAGAMENTOS ADD STATUS_PAG VARCHAR(20) NOT NULL;
ALTER TABLE PAGAMENTOS DROP COLUMN HORA_PAG TIME;
ALTER TABLE PAGAMENTOS MODIFY COLUMN  STATUS_PAG ENUM('PENDENTE', 'CONCLUIDO', 'EM ESPERA');
ALTER TABLE PAGAMENTOS CHANGE COLUMN CONFIRM_PAG ID_PAG INT PRIMARY KEY;

