CREATE SCHEMA EC2_SI1N

USE EC2_SI1N

CREATE TABLE IF NOT EXISTS PASSAGEIROS(
PASS_CPF INT PRIMARY KEY,
PASS_NOME VARCHAR(45) NOT NULL,
PASS_DATANASC DATE,  
PASS_TEL INT NOT NULL,
PASS_RUANUM INT NOT NULL,
PASS_BAIRRO VARCHAR(45) NOT NULL,
PASS_CIDADE VARCHAR(45) NOT NULL,
PASS_ESTADO VARCHAR(45) NOT NULL,
PASS_EMAIL VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS VOOS(
VOO_ID INT PRIMARY KEY,
DATAHORA_ORIGEM DATETIME NOT NULL,
DATAHORA_DESTINO DATETIME NOT NULL,
VOO_PILOTO VARCHAR(45) NOT NULL 
);

CREATE TABLE IF NOT EXISTS AEROPORTOS(
AEROP_ID INT PRIMARY KEY,
AEROP_NOME VARCHAR(45) NOT NULL, 
AEROP_LOCAL VARCHAR(15) NOT NULL,
AEROP_PAIS VARCHAR(45) NOT NULL,
AEROP_LONGITUDE DOUBLE NOT NULL,
AEROP_LATITUDE DOUBLE NOT NULL,
AEROP_FIAIS VARCHAR(45) 
);

CREATE TABLE IF NOT EXISTS AERONAVES(
AERONAVE_PREFIXO VARCHAR(10) NOT NULL,
AERONAVE_MODELO VARCHAR(20) NOT NULL,
AERONAVE_DATAFAB INT NOT NULL,
AERONAVE_CAPAC VARCHAR(20) NOT NULL,
AERONAVE_FABRIC VARCHAR(45) NOT NULL,
AERONAVE_ESPECCARACT TEXT 
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS(
FUNC_ID INT PRIMARY KEY,
FUNC_FUNCAO VARCHAR(45) NOT NULL,
FUNC_NOME VARCHA(45) NOT NULL,
FUNC_DATANASC DATE NOT NULL,
FUNC_CONTAC INT NOT NULL
);

CREATE TABLE IF NOT EXISTS RESERVAS(
VOO_ID INT,
PASS_CPF INT,
PRIMARY KEY(VOO_ID, PASS_CPF),
CONSTRAINT VOO_FK_ID FOREIGN KEY(VOO_ID)
REFERENCES VOOS(VOO_ID),
CONSTRAINT PASS_FK_CPF FOREIGN KEY(PASS_CPF)
REFERENCES PASSAGEIROS(PASS_CPF)
);

CREATE TABLE IF NOT EXISTS EQUIPES(
FUNC_ID INT,
VOO_ID INT,
CONSTRAINT FUNC_FK_ID FOREIGN KEY(FUNC_ID)
REFERENCES FUNCIONARIOS(FUNC_ID),
CONSTRAINT VOO_FK_ID FOREIGN KEY(VOO_ID)
REFERENCES VOOS(VOO_ID),
);  

ALTER TABLE PASSAGEIROS ADD PASS_CONTAC VARCHAR(20) NOT NULL;
ALTER TABLE PASSAGEIROS DROP COLUMN PASS_DATANASC DATE;
ALTER TABLE PASSAGEIROS MODIFY COLUMN PASS_NOME VARCHAR(30) NOT NULL;
ALTER TABLE PASSAGEIROS CHANGE COLUMN PASS_NOME PASS_NOMECOMP VARCHAR(30) NOT NULL;

ALTER TABLE VOOS ADD VOO_ESPEC VARCHAR(45);
ALTER TABLE VOOS DROP COLUMN VOO_PILOTO VARCHAR(45) NOT NULL; 
ALTER TABLE VOOS MODIFY COLUMN VOO_ESPEC TEXT;
ALTER TABLE VOOS CHANGE COLUMN VOO_ID VOO_COD INT PRIMARY KEY,

ALTER TABLE AEROPORTOS ADD AEROP_ESTADO VARCHAR(45) NOT NULL; 
ALTER TABLE AEROPORTOS DROP COLUMN AEROP_FIAIS VARCHAR(45); 
ALTER TABLE AEROPORTOS MODIFY COLUMN AEROP_LOCAL VARCHAR(45) NOT NULL;
ALTER TABLE AEROPORTOS CHANGE COLUMN AEROP_ID AEROP_COD INT PRIMARY KEY;

ALTER TABLE AERONAVES ADD AERONAVE_ALTERACAO TEXT;
ALTER TABLE AERONAVES DROP COLUMN  AERONAVE_ESPECCARACT TEXT; 
ALTER TABLE AERONAVES MODIFY COLUMN AERONAVE_CAPAC INT NOT NULL;
ALTER TABLE AERONAVES CHANGE COLUMN AERONAVE_ANOFAB INT NOT NULL;

ALTER TABLE FUNCIONARIOS ADD FUNC_ALTERACAO VARCHAR(45);
ALTER TABLE FUNCIONARIOS DROP COLUMN FUNC_DATANASC DATE NOT NULL;
ALTER TABLE FUNCIONARIOS MODIFY COLUMN FUNC_ALTERACAO TEXT;
ALTER TABLE FUNCIONARIOS CHANGE COLUMN FUNC_CONTAC FUNC_TEL INT NOT NULL;

DROP TABLE RESERVAS;



