CREATE SCHEMA EC2_SI1N

USE EC2_SI1N

CREATE TABLE IF NOT EXISTS PASSAGEIROS(
PASS_CPF INT PRIMARY KEY,
PASS_NOME VARCHAR(45) NOT NULL,
PASS_TEL INT NOT NULL,
PASS_RUANUM INT NOT NULL,
PASS_BAIRRO VARCHAR(45) NOT NULL,
PASS_CIDADE VARCHAR(45) NOT NULL,
PASS_ESTADO VARCHAR(45) NOT NULL,
PASS_EMAIL VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS VOOS(
VOO_COD INT PRIMARY KEY,
DATAHORA_ORIGEM DATETIME NOT NULL,
DATAHORA_DESTINO DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS AEROPORTOS(
AEROP_COD
AEROP_NOME
AEROP_LOCAL
AEROP_PAIS
AEROP_LONGITUDE
AEROP_LATITUDE
CONSTRAINT FK_

);

CREATE TABLE IF NOT EXISTS AERONAVES(






  
);
