CREATE SCHEMA EC4_SI1N

USE EC4_SI1N

CREATE TABLE IF NOT EXISTS ALUNOS(
CPF_ALUNOS INT PRIMARY KEY,
NOME_ALUNO VARCHAR(45) NOT NULL,
DATA_NASC_ALUNO DATE NOT NULL,
RUA_NUM_ALUNO VARCHAR(20) NOT NULL,
BAIRRO_ALUNO VARCHAR(45) NOT NULL,
CIDADE_ALUNO VARCHAR(45) NOT NULL,
ESTADO_ALUNO VARCHAR(45) NOT NULL,
MODALID_ALUNO VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS INSTRUTORES(
ID_INST INT PRIMARY KEY,
NOME_INST VARCHAR(45) NOT NULL,
DATA_NASC_INST DATE NOT NULL,
RUA_NUM_INST VARCHAR(20) NOT NULL,
BAIRRO_INST VARCHAR(45) NOT NULL,
CIDADE_INST VARCHAR(45) NOT NULL,
ESTADO_INST VARCHAR(45) NOT NULL,
MODALID_INST VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS MODALIDADES(
COD_MODALID INT PRIMARY KEY,
NOME_MODALID VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS PLANOS DE TREINAMENTO(
ID_PLTR INT PRIMARY KEY,
DATA_PLTR DATE NOT NULL,
REGISTRO_PLTR TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS AULAS(
ID_AULA INT PRIMARY KEY,
MODAL_AULA VARCHAR(45) NOT NULL,
TIPO_AULA VARCHAR(45) NOT NULL,
DATAHORA_AULA DATETIME NOT NULL,
CAPAC_AULA VARCHAR(20) NOT NULL,
INSTRESP_AULAS VARCHAR(45) NOT NULL,
);

CREATE TABLE IF NOT EXISTS PAGAMENTOS(
CONFIRM_PAG INT PRIMARY KEY,
DATA_PAG DATE NOT NULL,
VALOR_PAG VARCHAR(20) NOT NULL,
STATUS_PAG VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS ALUNOS_AULAS(


CREATE TABLE IF NOT EXISTS INSTRUTORES_MODALIDADES(
